(()=>{
'use strict';
const $=s=>document.querySelector(s),e=SGP.esc;let data,loadError='',rollback=null,pending=null;
try{data=SGP.storage.load();const v=SGP.validate(data);if(v.errors.length)throw new Error(v.errors[0])}catch(err){data=SGP.empty();loadError='Não foi possível abrir a base local. O conteúdo original foi preservado. Exporte o backup de recuperação em Configurações antes de restaurar a demonstração.'}
const defaults={page:'Visão Geral',scale:'Mês',group:'front',closed:[],anchor:SGP.today().slice(0,7)+'-01',deliveryDays:30,capMode:'front',personMode:'pessoas',filters:{front:'',leader:'',pmo:'',plan:'',status:'',phase:'',risk:'',search:'',from:'',to:''}};
let saved={};try{saved=JSON.parse(localStorage.getItem('sgp-view')||'{}')}catch{}
const state={...defaults,...saved,filters:{...defaults.filters,...saved.filters},page:'Visão Geral'};
const paths=['M3 10l9-7 9 7v11H3z M9 21v-8h6v8','M4 5h16v16H4z M4 10h16 M8 2v6 M16 2v6','M8 6h13 M8 12h13 M8 18h13 M3 6h1 M3 12h1 M3 18h1','M3 20v-8 M9 20V4 M15 20v-6 M21 20V8','M3 4h18l-7 9v7l-4-2v-5z','M16 21v-3a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v3 M9 3a4 4 0 1 0 0 8a4 4 0 1 0 0-8 M19 8v6 M16 11h6','M4 3v18h18 M8 16l4-6 4 3 5-8','M12 8a4 4 0 1 0 0 8a4 4 0 1 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2'];
const menu=['Visão Geral','Cronograma','Demandas','Capacidade','Pipeline','Pessoas','Relatórios','Configurações'];
$('#nav').innerHTML=menu.map((p,i)=>`<button data-page="${p}" title="${p}"><svg viewBox="0 0 24 24"><path d="${paths[i]}"/></svg><span>${p}</span></button>`).join('');
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200)}
function persistView(){try{localStorage.setItem('sgp-view',JSON.stringify(state))}catch{toast('Não foi possível salvar as preferências neste navegador.')}}
function commit(next){try{SGP.storage.save(next);data=next;loadError='';render();return true}catch(err){toast('Não foi possível salvar. Exporte um backup ou libere espaço no navegador.');return false}}
function period(){const today=SGP.today(),start=state.filters.from||(state.filters.to||today).slice(0,7)+'-01',d=SGP.date(start),end=state.filters.to||SGP.iso(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)));return {start,end}}
function filtered(){const f=state.filters;return data.demandas.filter(d=>Object.entries(f).every(([k,v])=>!v||k==='search'?(k!=='search'||!v||`${d.code} ${d.name} ${d.description}`.toLocaleLowerCase('pt-BR').includes(v.toLocaleLowerCase('pt-BR'))):k==='from'?d.end>=v:k==='to'?d.start<=v:d[k]===v))}
function options(values,current,empty='Todos'){return `<option value="">${empty}</option>`+values.map(v=>`<option value="${e(v)}" ${v===current?'selected':''}>${e(v)}</option>`).join('')}
function renderFilters(){const f=state.filters,fields=[['front','Frente',SGP.fronts],['leader','Tech Leader',[...new Set(data.demandas.map(d=>d.leader).filter(Boolean))]],['pmo','PMO',[...new Set(data.demandas.map(d=>d.pmo).filter(Boolean))]],['plan','Plan',[...new Set(data.demandas.map(d=>d.plan).filter(Boolean))]],['status','Status',SGP.statuses],['phase','Fase',SGP.stages],['risk','Risco',['Nenhum','Baixa','Média','Alta','Crítica']]];
 $('#filters').innerHTML=fields.map(([key,label,values])=>`<label>${label}<select data-filter="${key}" class="${f[key]?'filter-active':''}">${options(values,f[key])}</select></label>`).join('')+`<label>De <input aria-label="Período inicial" type="date" data-filter="from" value="${e(f.from)}"></label><label>Até <input aria-label="Período final" type="date" data-filter="to" value="${e(f.to)}"></label><button data-action="clear-filters">Limpar filtros</button><span id="filter-count">${Object.values(f).filter(Boolean).length?Object.values(f).filter(Boolean).length+' filtro(s) ativo(s)':'Todas as frentes'}</span>`;
 $('#filters').hidden=state.page==='Configurações';
}
const title=(t,sub='',actions='')=>`<div class="section-title"><div><h2>${t}</h2>${sub?`<p>${sub}</p>`:''}</div><div class="actions">${actions}</div></div>`;
function render(){
 persistView();renderFilters();$('#page-label').textContent=state.page;$('#updated').textContent=new Date(data.updated).toLocaleString('pt-BR');$('#demo-label').hidden=data.settings?.demo===false;document.querySelectorAll('#nav button').forEach(b=>{b.classList.toggle('active',b.dataset.page===state.page);b.setAttribute('aria-current',b.dataset.page===state.page?'page':'false')});
 const ds=filtered(),{start,end}=period();let html='';
 if(state.page==='Visão Geral')html=SGP.dashboard(data,ds,state,start,end);
 if(state.page==='Cronograma')html=title('Cronograma executivo','Do início da demanda à entrega final. Clique em uma demanda para consultar suas fases e marcos.')+SGP.timeline(data,ds,state);
 if(state.page==='Demandas')html=title('Demandas',`${ds.length} de ${data.demandas.length} demandas · visão ponta a ponta`,'<button class="primary" data-new="demandas">＋ Nova demanda</button>')+`<div style="margin-bottom:14px"><input id="search" aria-label="Buscar demandas" placeholder="Buscar código, nome ou descrição…" value="${e(state.filters.search)}" style="width:min(420px,100%)"></div>`+SGP.panel('Portfólio de demandas',SGP.table(['Código / Demanda','Frente','Tech Leader','Fase atual','Status','Entrega técnica','Entrega final','Conclusão','Risco'],ds.map(d=>[`<button class="link" data-detail="${e(d.id)}"><b>${e(d.code)}</b> · ${e(d.name)}</button>`,e(d.front),e(d.leader),e(d.phase),SGP.badge(d.status),SGP.fmt(d.technical),SGP.fmt(d.end),(Number(d.progress)||0)+'%',SGP.badge(d.risk||'Nenhum')])));
 if(state.page==='Capacidade'){
  const caps=SGP.capacity(data,start,end,ds).filter(p=>!state.filters.front||p.front===state.filters.front),fc=SGP.frontCapacity(caps);
  html=title('Capacidade da operação',`${SGP.fmt(start)} a ${SGP.fmt(end)}/${end.slice(0,4)} · horas proporcionais ao período`, '<button class="primary" data-new="alocacoes">＋ Nova alocação</button>')+`<div class="panel"><div class="subtabs"><button data-cap-mode="front" class="${state.capMode==='front'?'active':''}">Por frente</button><button data-cap-mode="person" class="${state.capMode==='person'?'active':''}">Por pessoa</button></div>`+(state.capMode==='front'?SGP.capacityTable(fc):SGP.table(['Pessoa','Frente','Disponível','Alocadas','Utilização','Situação','Demandas / período'],caps.map(p=>[e(p.name),e(p.front),Math.round(p.available)+'h',Math.round(p.hours)+'h',SGP.util(p.util),SGP.badge(p.conflict?'Sobrealocação':p.util>=90?'Atenção':p.util<80?'Disponível':'Saudável'),p.allocations.map(a=>`<button class="link" data-detail="${e(a.demand)}">${e(data.demandas.find(d=>d.id===a.demand)?.code)}</button> <small>${SGP.fmt(a.start)}–${SGP.fmt(a.end)}</small>`).join('<br>')||'—'])))+`<div class="note">Capacidade mensal proporcional aos dias corridos. Horas alocadas distribuídas uniformemente pelo intervalo; feriados não são descontados. Sobreposição entre demandas só caracteriza sobrealocação quando excede a capacidade diária. ${Object.values(state.filters).some(Boolean)?'Filtros ativos: as horas exibidas consideram apenas as demandas selecionadas.':''}</div></div>`;
 }
 if(state.page==='Pipeline')html=title('Pipeline de demandas','Clique em uma etapa para abrir as demandas correspondentes.')+SGP.panel('Distribuição por fase',SGP.pipeline(ds))+SGP.panel('Tempo na operação',SGP.table(['Demanda','Fase','Status','Dias desde entrada','Dependência'],ds.map(d=>[`<button class="link" data-detail="${e(d.id)}">${e(d.code)} · ${e(d.name)}</button>`,e(d.phase),SGP.badge(d.status),d.entry?Math.max(0,SGP.days(d.entry,SGP.today())-1):'—',e(d.dependency||'—')])));
 if(state.page==='Pessoas'){
  const ps=data.pessoas.filter(p=>(!state.filters.front||p.front===state.filters.front)&&(!state.filters.leader||p.leader===state.filters.leader)),ids=new Set(ds.map(d=>d.id));
  html=title('Pessoas e alocações','Pessoas, capacidade mensal e participação nas demandas.',`<button data-new="pessoas">＋ Nova pessoa</button><button class="primary" data-new="alocacoes">＋ Nova alocação</button>`)+`<div class="panel"><div class="subtabs"><button data-person-mode="pessoas" class="${state.personMode==='pessoas'?'active':''}">Pessoas</button><button data-person-mode="alocacoes" class="${state.personMode==='alocacoes'?'active':''}">Alocações</button></div>`+(state.personMode==='pessoas'?SGP.table(['Nome','Função','Frente principal','Tech Leader','Capacidade mensal','Ativo',''],ps.map(p=>[e(p.name),e(p.role),e(p.front),e(p.leader),p.capacity+'h',e(p.active),`<button data-edit="pessoas" data-id="${e(p.id)}">Editar</button>`])):SGP.table(['Pessoa','Demanda','Início','Fim','Horas','Percentual',''],data.alocacoes.map((a,i)=>({...a,index:i})).filter(a=>ids.has(a.demand)).map(a=>[e(data.pessoas.find(p=>p.id===a.person)?.name),`<button class="link" data-detail="${e(a.demand)}">${e(data.demandas.find(d=>d.id===a.demand)?.code)}</button>`,SGP.fmt(a.start),SGP.fmt(a.end),a.hours+'h',a.percent!==''&&a.percent!=null?a.percent+'%':'—',`<button data-edit="alocacoes" data-index="${a.index}">Editar</button>`])))+'</div>';
 }
 if(state.page==='Marcos'){
  const deliveries=SGP.deliveries(data,ds,Number(state.deliveryDays));html=title('Próximas entregas','Entrega técnica, go-live e entrega final em perspectivas distintas.',`<label>Janela <select id="delivery-days">${[15,30,60,90].map(n=>`<option value="${n}" ${Number(state.deliveryDays)===n?'selected':''}>${n} dias</option>`).join('')}</select></label><button class="primary" data-new="marcos">＋ Novo marco</button>`)+SGP.panel('Próximos marcos',SGP.table(['Data','Demanda','Frente','Marco','Status'],deliveries.map(m=>[SGP.fmt(m.date),`<button class="link" data-detail="${e(m.demand)}">${e(m.d.code)} · ${e(m.d.name)}</button>`,e(m.d.front),e(m.name),SGP.badge(m.status)])));
 }
 if(state.page==='Riscos'){const risks=SGP.risks(data,ds,SGP.capacity(data,start,end,ds));html=title('Atenções e riscos',`${risks.length} atenções identificadas para atuação do Business Operations`)+SGP.panel('Pontos de atenção',SGP.table(['Demanda','Frente','Atenção','Descrição','Severidade'],risks.map(r=>[`<button class="link" data-detail="${e(r.d.id)}">${e(r.d.code)} · ${e(r.d.name)}</button>`,e(r.d.front),SGP.badge(r.type),e(r.description),SGP.badge(r.severity)])))}
 if(state.page==='Relatórios')html=title('Relatórios da operação','Relatório do recorte atual. A exportação Excel sempre contém toda a base.', '<button data-action="print">Imprimir / Salvar PDF</button>')+SGP.panel('Capacidade por frente',SGP.capacityTable(SGP.frontCapacity(SGP.capacity(data,start,end,ds).filter(p=>!state.filters.front||p.front===state.filters.front))))+SGP.panel('Entregas técnicas × entregas finais',SGP.table(['Demanda','Frente','Entrega técnica','Entrega final','Intervalo após técnica','Dependência','Responsável'],ds.map(d=>[e(d.code+' · '+d.name),e(d.front),SGP.fmt(d.technical),SGP.fmt(d.end),d.technical?Math.max(0,SGP.days(d.technical,d.end)-1)+' dias':'—',e(d.dependency||'—'),e(d.dependencyOwner||'—')])));
 if(state.page==='Configurações')html=title('Configurações','Armazenamento local, segurança dos dados e recuperação.')+`<section class="panel settings"><div><h3>Dados neste navegador</h3><p>A base é exclusiva deste navegador e desta origem. Não há sincronização entre pessoas ou dispositivos. Exporte regularmente para preservar seu trabalho.</p><div class="counts">${Object.keys(SGP.schemas).map(k=>`<span><b>${data[k].length}</b>${SGP.sheetNames[k]}</span>`).join('')}</div><div class="actions"><button data-action="backup">Exportar backup JSON</button><button data-action="import-json">Importar backup JSON</button><button data-action="rollback" ${rollback?'':'disabled'}>Desfazer última importação</button>${loadError?'<button data-action="recovery">Exportar backup de recuperação</button>':''}</div></div><div><h3>Dados de demonstração</h3><p>Exemplos fictícios das cinco frentes. Restaurar substitui a base atual e solicita confirmação.</p><button data-action="restore">Restaurar dados de demonstração</button></div><div><h3>Limpar base</h3><p>Remove demandas, pessoas, alocações, fases e marcos deste navegador. Baixe um backup antes de continuar.</p><button class="danger" data-action="clear">Limpar dados locais</button></div><div><h3>Sobre esta versão</h3><p>V1 · aplicação standalone · Excel e armazenamento local.<br>Sem autenticação ou integração automática com ferramentas técnicas. Datas das fases são independentes; marcos complementam a visão de ponta a ponta.</p></div></section>`;
 $('#content').innerHTML=(loadError?`<p class="callout">${e(loadError)}</p>`:'')+html;
}
function modal(name,body,actions=''){const d=$('#dialog');if(d.open)d.close();$('#dialog-content').innerHTML=`<div class="modal-head"><h2 id="dialog-title">${e(name)}</h2><button data-action="close" aria-label="Fechar">×</button></div>${body}${actions?`<div class="modal-actions">${actions}</div>`:''}`;d.showModal()}
function confirmAction(name,text,fn){modal(name,`<div class="modal-body"><p>${e(text)}</p></div>`,'<button data-action="close">Cancelar</button><button id="confirm-action" class="primary">Confirmar</button>');$('#confirm-action').onclick=()=>{if(fn()!==false)$('#dialog').close()}}
function detail(id){const d=data.demandas.find(d=>d.id===id);if(!d)return;
 const body=`<div class="modal-body"><div class="detail-grid">${[['Frente',d.front],['Tech Leader',d.leader],['Fase',d.phase],['Status',d.status],['Início',SGP.fmt(d.start)],['Entrega técnica',SGP.fmt(d.technical)],['Implantação',SGP.fmt(d.deployment)],['Entrega final',SGP.fmt(d.end)]].map(([k,v])=>`<p><small>${k}</small><b>${e(v||'—')}</b></p>`).join('')}</div><div class="callout">${e(d.description||'Sem descrição.')}<br><strong>${d.technical?`${Math.max(0,SGP.days(d.technical,d.end)-1)} dias entre a entrega técnica e a entrega final.`:'Entrega técnica ainda não informada.'}</strong></div>${d.dependency?`<p>Dependência: ${e(d.dependency)} · ${e(d.dependencyOwner||'Responsável não informado')}</p>`:''}${d.riskDescription?`<p>${SGP.badge(d.risk)} ${e(d.riskDescription)}</p>`:''}${d.git?`<p><a href="${e(d.git)}" target="_blank" rel="noopener noreferrer">Abrir detalhamento técnico ↗</a></p>`:''}<details><summary>Todos os dados da demanda</summary><div class="detail-grid">${SGP.schemas.demandas.map(([f,l])=>`<p><small>${l}</small>${e(d[f]??'—')}</p>`).join('')}</div></details><h3>Fases <button data-new="fases" data-demand="${e(id)}">＋ Adicionar</button></h3>${SGP.table(['Fase','Início','Fim','Status',''],data.fases.map((p,i)=>({...p,index:i})).filter(p=>p.demand===id).map(p=>[e(p.phase),SGP.fmt(p.start),SGP.fmt(p.end),SGP.badge(p.status),`<button data-edit="fases" data-index="${p.index}">Editar</button>`]))}<h3>Marcos <button data-new="marcos" data-demand="${e(id)}">＋ Adicionar</button></h3>${SGP.table(['Marco','Data','Status',''],data.marcos.map((m,i)=>({...m,index:i})).filter(m=>m.demand===id).map(m=>[e(m.name),SGP.fmt(m.date),SGP.badge(m.status),`<button data-edit="marcos" data-index="${m.index}">Editar</button>`]))}<h3>Pessoas alocadas <button data-new="alocacoes" data-demand="${e(id)}">＋ Adicionar</button></h3>${SGP.table(['Pessoa','Início','Fim','Horas',''],data.alocacoes.map((a,i)=>({...a,index:i})).filter(a=>a.demand===id).map(a=>[e(data.pessoas.find(p=>p.id===a.person)?.name),SGP.fmt(a.start),SGP.fmt(a.end),a.hours+'h',`<button data-edit="alocacoes" data-index="${a.index}">Editar</button>`]))}</div>`;
 modal(d.code+' · '+d.name,body,`<button data-action="close">Fechar</button><button class="primary" data-edit="demandas" data-id="${e(id)}">Editar demanda</button>`);
}
function edit(key,index=-1,demand=''){
 const exists=index>=0,record=exists?data[key][index]:{id:SGP.uid(),start:SGP.today(),end:SGP.add(SGP.today(),30),date:SGP.today(),demand,status:'Não iniciado',phase:'Levantamento',front:SGP.fronts[0],type:'Projeto',risk:'Nenhum',role:'Analista',active:'Sim',capacity:160,progress:0,estimated:0,consumed:0,hours:0};
 const schema=SGP.schemas[key];
 function field([f,label,type]){const value=record[f]??'',required=type==='required'||type?.endsWith('!');let list=null;
  if(f==='front')list=SGP.fronts;if(f==='status')list=SGP.statuses;if(f==='phase')list=SGP.stages;if(f==='type')list=['Projeto','Proposta','Melhoria','Evolução','Ticket N3','Outro'];if(f==='risk')list=['Nenhum','Baixa','Média','Alta','Crítica'];if(f==='role')list=['Tech Leader','Analista','Desenvolvedor','PMO','Plan','Business Operations','Outro'];if(f==='active')list=['Sim','Não'];
  let input;if(f==='person'||f==='demand'){const source=f==='person'?data.pessoas:data.demandas;input=`<select name="${f}" required><option value="">Selecione</option>${source.map(x=>`<option value="${e(x.id)}" ${x.id===value?'selected':''}>${e(x.code?x.code+' · '+x.name:x.name)}</option>`).join('')}</select>`}else if(list)input=`<select name="${f}" ${required?'required':''}>${list.map(x=>`<option ${x===value?'selected':''}>${e(x)}</option>`).join('')}</select>`;else input=`<input name="${f}" value="${e(value)}" type="${type?.startsWith('date')?'date':type?.startsWith('number')||type==='percent'?'number':f==='git'?'url':'text'}" ${required?'required':''} ${type?.startsWith('number')||type==='percent'?'min="0" step="any"':''} ${type==='percent'?'max="100"':''} ${f==='id'&&exists?'readonly':''}>`;
  return `<label class="field ${['description','riskDescription','notes','dependency'].includes(f)?'wide':''}">${e(label)}${required?' *':''}${input}</label>`;
 }
 modal(`${exists?'Editar':'Adicionar'} · ${SGP.sheetNames[key]}`,`<form id="record-form"><div class="modal-body"><div class="form-grid">${schema.map(field).join('')}</div><p id="form-error" class="form-error" role="alert"></p></div><div class="modal-actions">${exists?'<button type="button" id="delete-record" class="danger">Excluir</button>':''}<button type="button" data-action="close">Cancelar</button><button class="primary" type="submit">Salvar</button></div></form>`);
 $('#record-form').onsubmit=event=>{event.preventDefault();const values=new FormData(event.currentTarget),r={};schema.forEach(([f,,type])=>{const val=String(values.get(f)??'').trim();r[f]=(type?.startsWith('number')||type==='percent')&&val!==''?Number(val):val});const next=structuredClone(data);if(exists)next[key][index]=r;else next[key].push(r);const result=SGP.validate(next);if(result.errors.length){$('#form-error').textContent=result.errors.join('\n');return}if(result.warnings.length){confirmAction('Salvar com avisos?',result.warnings.join('\n'),()=>{if(commit(next)){toast('Registro salvo.');return true}return false})}else if(commit(next)){$('#dialog').close();toast('Registro salvo.')}};
 if(exists)$('#delete-record').onclick=()=>{const dependent=key==='demandas'?data.alocacoes.some(a=>a.demand===record.id)||data.fases.some(a=>a.demand===record.id)||data.marcos.some(a=>a.demand===record.id):key==='pessoas'?data.alocacoes.some(a=>a.person===record.id):false;if(dependent){$('#form-error').textContent='Este registro possui referências. Remova as alocações, fases e marcos vinculados antes de excluir.';return}confirmAction('Excluir registro?','Esta ação removerá o registro da base local.',()=>{const next=structuredClone(data);next[key].splice(index,1);return commit(next)})};
}
async function importFile(file){if(!file)return;try{if(file.size>20*1024*1024)throw new Error('O arquivo supera 20 MB.');let result;if(file.name.toLowerCase().endsWith('.json')){const parsed=JSON.parse(await file.text());result={data:parsed,...SGP.validate(parsed)}}else result=SGP.parseWorkbook(XLSX.read(await file.arrayBuffer(),{type:'array'}));pending=result;
 modal('Pré-validação da importação',`<div class="modal-body"><p>Arquivo analisado: <strong>${e(file.name)}</strong></p><div class="counts">${Object.keys(SGP.schemas).map(k=>`<span><b>${result.data[k]?.length||0}</b>${SGP.sheetNames[k]}</span>`).join('')}</div><p>${result.errors.length} erro(s) crítico(s) · ${result.warnings.length} aviso(s)</p><div class="issues">${result.errors.map(x=>`<div style="color:#c13e54">✕ ${e(x)}</div>`).join('')}${result.warnings.map(x=>`<div style="color:#9d6a12">⚠ ${e(x)}</div>`).join('')}${!result.errors.length&&!result.warnings.length?'<p>✓ Estrutura, datas e referências válidas.</p>':''}</div><p>A importação substituirá toda a base atual. Você poderá desfazer em Configurações durante esta sessão.</p>${result.warnings.length?'<label><input id="accept-warnings" type="checkbox"> Li os avisos e desejo continuar.</label>':''}</div>`,`<button data-action="close">Cancelar</button><button id="confirm-import" class="primary" ${result.errors.length||result.warnings.length?'disabled':''}>Confirmar importação</button>`);
 if($('#accept-warnings'))$('#accept-warnings').onchange=ev=>$('#confirm-import').disabled=!!result.errors.length||!ev.target.checked;
 $('#confirm-import').onclick=()=>{if(pending.errors.length||pending.warnings.length&&!$('#accept-warnings').checked)return;const previous=structuredClone(data),next={...pending.data,settings:{...pending.data.settings,demo:false},version:1};if(commit(next)){rollback=previous;pending=null;$('#dialog').close();toast('Importação concluída.');render()}};
 }catch(err){modal('Não foi possível importar',`<div class="modal-body"><p class="form-error">${e(err.message||'Arquivo inválido ou incompatível.')}</p><p>A base atual foi preservada.</p></div>`,'<button data-action="close">Fechar</button>')}}
 document.addEventListener('click',ev=>{
  const b=ev.target.closest('button');if(!b)return;const a=b.dataset;
  if(a.page){state.page=a.page;render()}
  if(a.detail)detail(a.detail);
  if(a.new)edit(a.new,-1,a.demand||'');
  if(a.edit)edit(a.edit,a.index!==undefined?Number(a.index):data[a.edit].findIndex(r=>r.id===a.id));
  if(a.group){state.group=a.group;render()}
  if(a.collapseGroup){const idx=state.closed.indexOf(a.collapseGroup);if(idx>=0)state.closed.splice(idx,1);else state.closed.push(a.collapseGroup);render()}
  if(a.period!==undefined){const n=Number(a.period);if(!n)state.anchor=SGP.today().slice(0,7)+'-01';else if(state.scale==='Semana')state.anchor=SGP.add(state.anchor,n*28);else{const d=SGP.date(state.anchor);state.anchor=SGP.iso(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+n*(state.scale==='Trimestre'?3:1),1)))}render()}
  if(a.pipeline){state.filters.phase=a.pipeline;state.page='Demandas';render()}
  if(a.capMode){state.capMode=a.capMode;render()}
  if(a.personMode){state.personMode=a.personMode;render()}
  if(a.action==='close')$('#dialog').close();
  if(a.action==='clear-filters'){state.filters={...defaults.filters};render()}
  if(a.action==='model'){try{SGP.exportExcel(SGP.demo(),'Modelo-SGP.xlsx');toast('Modelo Excel gerado.')}catch{toast('Não foi possível gerar o modelo Excel.')}}
  if(a.action==='export'){try{SGP.exportExcel(data);toast('Base exportada para Excel.')}catch{toast('Não foi possível exportar o Excel.')}}
  if(['import','import-json'].includes(a.action)){$('#file').accept=a.action==='import-json'?'.json':'.xlsx';$('#file').click()}
  if(a.action==='backup')SGP.download('SGP-backup.json',JSON.stringify(data,null,2),'application/json');
  if(a.action==='recovery')SGP.download('SGP-recuperacao.json',localStorage.getItem(SGP.storage.key)||'','application/json');
  if(a.action==='print')window.print();
  if(a.action==='restore')confirmAction('Restaurar demonstração?','A base atual será substituída por dados fictícios. Exporte um backup se desejar preservá-la.',()=>{const next=SGP.demo();next.settings.demo=true;return commit(next)});
  if(a.action==='clear')confirmAction('Limpar todos os dados locais?','Todas as demandas, pessoas, alocações, fases e marcos serão removidos. Essa ação não pode ser desfeita.',()=>{const next=SGP.empty();next.settings.demo=false;if(commit(next)){rollback=null;render();return true}return false});
  if(a.action==='rollback'&&rollback)confirmAction('Desfazer importação?','A base anterior à última importação será restaurada. Alterações feitas depois dela serão perdidas.',()=>{if(commit(rollback)){rollback=null;render();return true}return false});
 });
 document.addEventListener('change',ev=>{const el=ev.target;if(el.dataset.filter){const key=el.dataset.filter,old=state.filters[key];state.filters[key]=el.value;if(state.filters.from&&state.filters.to&&state.filters.from>state.filters.to){state.filters[key]=old;el.value=old;toast('A data final deve ser igual ou posterior à inicial.');return}if(key==='from'&&el.value)state.anchor=el.value.slice(0,7)+'-01';render()}if(el.id==='scale'){state.scale=el.value;render()}if(el.id==='delivery-days'){state.deliveryDays=Number(el.value);render()}if(el.id==='file'){importFile(el.files[0]);el.value=''}});
 document.addEventListener('input',ev=>{if(ev.target.id==='search'){const value=ev.target.value,pos=ev.target.selectionStart;state.filters.search=value;render();$('#search').focus();$('#search').setSelectionRange(pos,pos)}});
 $('#collapse').onclick=()=>{document.body.classList.toggle('collapsed');$('#collapse').setAttribute('aria-expanded',String(!document.body.classList.contains('collapsed')))};
 if(!loadError&&!localStorage.getItem(SGP.storage.key)){try{SGP.storage.save(data)}catch{loadError='Armazenamento local indisponível. Exporte os dados antes de fechar.'}}
 render();
 const context=document.modelContext;
 if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'read_sgp_operation',title:'Consultar operação SGP',description:'Retorna as demandas do recorte visível e os totais de capacidade do período selecionado.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||Object.keys(input).length)throw new Error('Nenhum parâmetro é aceito.');const {start,end}=period(),ds=filtered();return {demands:ds.map(d=>({code:d.code,name:d.name,status:d.status,technical:d.technical,end:d.end})),capacity:SGP.frontCapacity(SGP.capacity(data,start,end,ds).filter(p=>!state.filters.front||p.front===state.filters.front)),period:{start,end}}}})).catch(()=>{})}catch{}}
})();
