SGP.badge=s=>`<span class="badge ${/risco|Bloqueado|Alta|Sobrealoc/.test(s)?'red':/Aguardando|Média|Atenção/.test(s)?'amber':/Concluído|Saudável|Disponível/.test(s)?'green':''}">${SGP.esc(s)}</span>`;
SGP.table=(headers,rows,compact=false)=>`<div class="table-wrap"><table class="${compact?'compact':''}"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map(c=>`<td>${c}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${headers.length}" class="empty">Nenhum registro encontrado.</td></tr>`}</tbody></table></div>`;
SGP.panel=(title,body,action='')=>`<section class="panel"><div class="panel-head"><h2>${title}</h2>${action}</div>${body}</section>`;
SGP.util=u=>Number.isFinite(u)?Math.round(u)+'%':'Sem capacidade';
SGP.capacityTable=(rows,compact=false)=>SGP.table(['Frente','Pessoas','Disponível','Alocadas','Utilização'],rows.map((r,i)=>[`<span class="dot" style="background:${SGP.colors[i]}"></span>${SGP.esc(r.front)}`,r.people,Math.round(r.available)+'h',Math.round(r.hours)+'h',`<div class="capacity-bar"><div class="bar-bg"><i style="width:${Math.min(100,r.util)}%;background:${r.util>100?'#ec5268':r.util>=90?'#e8ac36':'#2cbc8a'}"></i></div><span>${SGP.util(r.util)} ${r.util>100?'⚠':''}</span></div>`]),compact);
SGP.deliveries=(data,ds,days=30)=>{const ids=new Set(ds.filter(d=>!['Concluído','Cancelado'].includes(d.status)).map(d=>d.id)),today=SGP.today(),end=SGP.add(today,days),map=new Map(ds.map(d=>[d.id,d]));const result=data.marcos.filter(m=>ids.has(m.demand)&&m.date>=today&&m.date<=end&&m.status!=='Concluído').map(m=>({...m,d:map.get(m.demand)}));ds.filter(d=>ids.has(d.id)).forEach(d=>{[['Entrega técnica',d.technical],['Entrega final',d.end], [d.next,d.nextDate]].forEach(([name,date])=>{if(name&&date>=today&&date<=end&&!result.some(m=>m.demand===d.id&&m.name===name&&m.date===date)&&!data.marcos.some(m=>m.demand===d.id&&m.name===name&&m.date===date))result.push({demand:d.id,name,date,status:d.status,d})})});return result.sort((a,b)=>a.date.localeCompare(b.date))};
// Diagnostic signals use entered totals; they do not predict delivery automatically.
SGP.executionRisks=(data,ds)=>{
 const result=[],today=SGP.today(),active=ds.filter(d=>!['Concluído','Cancelado'].includes(d.status));
 for(const d of active){
  const estimated=Number(d.estimated),consumed=Number(d.consumed),progress=Number(d.progress),hasProgress=d.progress!==''&&d.progress!=null&&Number.isFinite(progress)&&progress>=0&&progress<=100;
  const add=(type,severity,description)=>result.push({d,type,severity,description,execution:true});
  if(estimated>0&&Number.isFinite(estimated)&&Number.isFinite(consumed)&&consumed>=0){
   const used=consumed/estimated*100,gap=used-progress;
   if(consumed>estimated)add('Horas excedidas','Alta',`${consumed}h consumidas de ${estimated}h estimadas: ${Math.round(used)}% do orçamento de horas. Excesso de ${Math.round((consumed-estimated)*10)/10}h. Revise esforço restante e estimativa.`);
   else if(hasProgress&&used>=50&&gap>=20)add('Consumo acima da evolução',gap>=40?'Alta':'Média',`${consumed}h de ${estimated}h (${Math.round(used)}% das horas) para ${progress}% concluído: diferença de ${Math.round(gap)} pontos percentuais. Confirme o avanço e revise o esforço restante.`);
  }
  for(const p of data.fases.filter(p=>p.demand===d.id&&!['Concluído','Cancelado'].includes(p.status)&&p.end<today))add('Fase vencida','Alta',`${p.phase}: término previsto em ${SGP.fmt(p.end)}, há ${SGP.days(p.end,today)-1} dia(s), com status ${p.status}. Atualize a fase ou revise o prazo.`);
 }
 return result;
};
SGP.executionPanel=risks=>{
 const rows=risks.filter(r=>r.execution).sort((a,b)=>(a.severity==='Alta'?0:1)-(b.severity==='Alta'?0:1));if(!rows.length)return '';
 const e=SGP.esc;
 return `<section class="panel execution-alerts"><div class="panel-head"><h2>⚠ Atenção à execução · ${new Set(rows.map(r=>r.d.id)).size} demanda(s)</h2><button data-page="Riscos">Ver todos os alertas (${rows.length})</button></div><div class="execution-list">${rows.slice(0,3).map(r=>`<article class="execution-item ${r.severity==='Alta'?'high':''}"><button class="link" data-detail="${e(r.d.id)}">${e(r.d.code)} · ${e(r.d.name)}</button><strong>${e(r.type)} · ${e(r.severity)}</strong><p>${e(r.description)}</p></article>`).join('')}</div><details class="execution-help"><summary>Como os alertas são calculados</summary><p>Horas excedidas: consumo maior que a estimativa. Consumo acima da evolução: ao menos 50% das horas utilizadas e diferença de 20 pontos percentuais ou mais em relação à conclusão informada; a partir de 40 pontos, severidade alta. Fase vencida: data final anterior a hoje e status diferente de Concluído ou Cancelado.</p><p>Horas e conclusão são da demanda inteira, não de cada fase. São sinais para revisão: o esforço não precisa evoluir de forma linear. Atualize horas, percentual e status para refletir a situação real. Sem estimativa positiva ou percentual preenchido, a comparação de evolução não é calculada. Demandas concluídas ou canceladas ficam fora destes alertas.</p></details></section>`;
};
SGP.risks=(data,ds,caps)=>{
 const risks=SGP.executionRisks(data,ds);ds.filter(d=>!['Concluído','Cancelado'].includes(d.status)).forEach(d=>{if(d.risk&&d.risk!=='Nenhum'||['Em risco','Bloqueado','Aguardando cliente','Aguardando aprovação'].includes(d.status)||d.end<SGP.today())risks.push({d,type:d.end<SGP.today()?'Prazo vencido':d.dependency?'Dependência':d.status,severity:d.risk&&d.risk!=='Nenhum'?d.risk:'Média',description:d.riskDescription||d.dependency||'Revisar prazo e situação da demanda.'})});
 caps.filter(p=>p.conflict).forEach(p=>{const unique=new Set();p.allocations.forEach(a=>{if(unique.has(a.demand))return;unique.add(a.demand);const d=ds.find(d=>d.id===a.demand);if(d)risks.push({d,type:'Sobrealocação',severity:'Alta',description:p.name+': horas diárias acima da capacidade em parte do período.'})})});return risks;
};
SGP.pipeline=ds=>{const stages=SGP.stages;return `<div class="pipeline">${stages.map(p=>{const n=ds.filter(d=>d.phase===p).length;return `<button class="pipe" data-pipeline="${p}"><span>${p}</span><strong>${n}</strong><small>${ds.length?Math.round(n/ds.length*100):0}%</small></button>`}).join('')}</div>`};
SGP.dashboard=(data,ds,state,start,end)=>{
 const e=SGP.esc,caps=SGP.capacity(data,start,end,ds).filter(p=>!state.filters?.front||p.front===state.filters.front),fc=SGP.frontCapacity(caps),deliveries=SGP.deliveries(data,ds,state.deliveryDays||30),risks=SGP.risks(data,ds,caps),active=ds.filter(d=>!['Concluído','Cancelado'].includes(d.status)),available=caps.reduce((s,p)=>s+p.available,0),hours=caps.reduce((s,p)=>s+p.hours,0);
 const names=list=>list.map(d=>d.code+' · '+d.name).join('\n')||'Nenhuma demanda neste recorte';const kpiTips=[names(active),names(ds.filter(d=>d.status==='Em andamento')),names(ds.filter(d=>d.status==='Aguardando cliente')),names([...new Map(risks.map(r=>[r.d.id,r.d])).values()]),deliveries.map(m=>m.d.code+' · '+m.d.name+' — '+m.name).join('\n')||'Nenhuma entrega no período',caps.map(p=>p.name+' — '+p.front).join('\n')||'Nenhuma pessoa no recorte'];SGP.kpiTips=kpiTips;const kpis=[['▤',active.length,'Demandas ativas','Ciclo completo da operação'],['✓',ds.filter(d=>d.status==='Em andamento').length,'Em andamento','Execução em curso'],['◷',ds.filter(d=>d.status==='Aguardando cliente').length,'Aguardando cliente','Dependências externas'],['⚠',new Set(risks.map(r=>r.d.id)).size,'Demandas em risco','Requerem atenção'],['⚑',deliveries.length,'Próximas entregas',`Marcos em ${state.deliveryDays||30} dias`],['♧',caps.length,'Pessoas na operação',`${SGP.util(available?hours/available*100:0)} de utilização`]];
 const statusGroups=[['Em andamento','#339bed'],['Em risco','#ec5268'],['Aguardando cliente','#eab839'],['Concluído','#36bd8d'],['Outros','#a3b2c0']],counts=statusGroups.map(([s])=>s==='Outros'?ds.filter(d=>!statusGroups.slice(0,4).some(([x])=>x===d.status)).length:ds.filter(d=>d.status===s).length);let pos=0;const gradient=counts.map((n,i)=>{const old=pos;pos+=ds.length?n/ds.length*100:0;return `${statusGroups[i][1]} ${old}% ${pos}%`}).join(',');
 return `<div class="kpis">${kpis.map(([icon,n,label,sub],i)=>`<button class="kpi" type="button" data-action="kpi-details" data-kpi="${i}" aria-label="Abrir lista de ${e(label)}"><span class="kpi-icon">${icon}</span><span><strong>${n}</strong><p>${label}</p><small>${sub}</small></span></button>`).join('')}</div>${SGP.executionPanel(risks)}${SGP.timeline(data,ds,state)}<div class="mid-grid">${SGP.panel('Pipeline de demandas',SGP.pipeline(ds))}${SGP.panel('Status das demandas',`<div class="status-wrap"><div class="donut" style="background:conic-gradient(${ds.length?gradient:'#edf2f6 0% 100%'})"><div><strong>${ds.length}</strong><span>Total</span></div></div><div class="status-list">${statusGroups.map(([s,c],i)=>`<div><span><i class="dot" style="background:${c}"></i>${s}</span><b>${counts[i]}</b></div>`).join('')}</div></div>`)}${SGP.panel('Demandas por frente',`<div class="front-bars">${SGP.fronts.map((f,i)=>{const n=ds.filter(d=>d.front===f).length,max=Math.max(1,...SGP.fronts.map(f=>ds.filter(d=>d.front===f).length));return `<div class="front-bar"><span>${f.replace(' Industrial','').replace('Inovação ','')}</span><div class="bar-bg"><i style="width:${n/max*100}%;background:${SGP.colors[i]}"></i></div><b>${n}</b></div>`}).join('')}</div>`)}</div><div class="bottom-grid">${SGP.panel('Capacidade da equipe',SGP.capacityTable(fc,true),'<button class="link" data-page="Capacidade">Detalhar ↗</button>')}${SGP.panel(`Próximas entregas · ${state.deliveryDays||30} dias`,SGP.table(['Data','Demanda / Marco','Status'],deliveries.slice(0,5).map(m=>[SGP.fmt(m.date),`<button class="link" data-detail="${e(m.d.id)}">${e(m.d.code)} · ${e(m.d.name)}</button><div style="color:#8b9ba8;margin-top:4px">${e(m.name)}</div>`,SGP.badge(m.status)]),true),'<button class="link" data-page="Marcos">Ver todas</button>')}${SGP.panel('Atenções e riscos',SGP.table(['Demanda','Atenção'],risks.slice(0,5).map(r=>[`<button class="link" data-detail="${e(r.d.id)}">${e(r.d.code)} · ${e(r.d.name)}</button>`,SGP.badge(r.type)]),true),'<button class="link" data-page="Riscos">Ver todos</button>')}</div>`;
};
