SGP.timeline=(data,demands,state)=>{
 const {esc:e}=SGP;let start=state.anchor||SGP.today().slice(0,7)+'-01',n=state.scale==='Semana'?8:state.scale==='Trimestre'?4:4;
 if(state.scale==='Trimestre'){const d=SGP.date(start);start=SGP.iso(new Date(Date.UTC(d.getUTCFullYear(),Math.floor(d.getUTCMonth()/3)*3,1)))}else if(state.scale==='Semana'){const d=SGP.date(start);start=SGP.add(start,-((d.getUTCDay()+6)%7))}
 if(state.scale==='Semana'&&demands.length){
  const ids=new Set(demands.map(d=>d.id)),dates=demands.flatMap(d=>[d.start,d.end,d.technical,d.deployment]).concat(data.fases.filter(p=>ids.has(p.demand)).flatMap(p=>[p.start,p.end]),data.marcos.filter(m=>ids.has(m.demand)).map(m=>m.date)).filter(d=>SGP.validDate(d)).sort();
  if(dates.length){if(dates[0]<start){start=dates[0];const d=SGP.date(start);start=SGP.add(start,-((d.getUTCDay()+6)%7))}n=Math.max(8,Math.ceil(SGP.days(start,dates.at(-1))/7))}
 }
 const periods=[];let cursor=start;
 for(let i=0;i<n;i++){
  let end;if(state.scale==='Semana')end=SGP.add(cursor,6);else{const dt=SGP.date(cursor);end=SGP.iso(new Date(Date.UTC(dt.getUTCFullYear(),dt.getUTCMonth()+(state.scale==='Trimestre'?3:1),0)))}
  periods.push({start:cursor,end});cursor=SGP.add(end,1);
 }
 const end=periods.at(-1).end,total=SGP.days(start,end),left=d=>(SGP.days(start,d)-1)/total*100;
 const today=SGP.today(),todayLine=today>=start&&today<=end?`<span class="today-line" style="left:${left(today)}%"></span>`:'';
 const phasesBy=new Map(),marksBy=new Map();data.fases.forEach(p=>{if(!phasesBy.has(p.demand))phasesBy.set(p.demand,[]);phasesBy.get(p.demand).push(p)});data.marcos.forEach(m=>{if(!marksBy.has(m.demand))marksBy.set(m.demand,[]);marksBy.get(m.demand).push(m)});
 const row=d=>{
  const ps=phasesBy.get(d.id)||[],ms=[...(marksBy.get(d.id)||[])];[['Entrega técnica',d.technical],['Entrega final',d.end]].forEach(([name,date])=>{if(date&&!ms.some(m=>m.name===name&&m.date===date))ms.push({name,date})});
  return `<div class="trow"><div class="tlabel"><button data-detail="${e(d.id)}" title="${e(d.code+' · '+d.name)}">${e(d.code)} <span style="color:#91a3b2">·</span> ${e(d.name)}</button><span>${e(d.leader||'—')}</span><time>${SGP.fmt(d.start)}</time><time>${SGP.fmt(d.end)}</time></div><div class="track" style="--ticks:${n*4}">${todayLine}${ps.filter(p=>p.end>=start&&p.start<=end).map(p=>{const a=Math.max(0,left(p.start)),b=Math.min(100,left(SGP.add(p.end,1)));return `<button class="phase-bar" data-detail="${e(d.id)}" aria-label="${e(d.code+' '+p.phase+' '+SGP.fmt(p.start)+' a '+SGP.fmt(p.end))}" title="${e(p.phase)} · ${SGP.fmt(p.start)} a ${SGP.fmt(p.end)}" style="left:${a}%;width:${b-a}%;background:${SGP.phaseColors[SGP.stages.indexOf(p.phase)]||'#92a8b8'}"></button>`}).join('')}${!ps.length&&d.start<=end&&d.end>=start?`<span class="phase-bar" style="left:${Math.max(0,left(d.start))}%;width:${Math.min(100,left(SGP.add(d.end,1)))-Math.max(0,left(d.start))}%;background:#a3b4c4" title="Período da demanda; fases não cadastradas"></span>`:''}${ms.filter(m=>m.date>=start&&m.date<=end).map(m=>`<span class="milestone ${m.name==='Entrega técnica'?'tech':''}" title="${e(m.name)} · ${SGP.fmt(m.date)}" style="left:${left(m.date)}%"></span>`).join('')}</div></div>`;
 };
 const groups=state.group==='phase'?SGP.stages:SGP.fronts,key=state.group==='phase'?'phase':'front';
 return `<section class="panel timeline-panel"><div class="panel-head"><div class="tabs"><button data-group="front" class="${key==='front'?'active':''}">Cronograma por Frentes</button><button data-group="phase" class="${key==='phase'?'active':''}">Por Fase</button><button data-page="Marcos">Marcos</button></div><div class="timeline-controls"><span>${SGP.fmt(start)} – ${SGP.fmt(end)}/${end.slice(0,4)}</span><select id="scale" aria-label="Escala do cronograma">${['Semana','Mês','Trimestre'].map(v=>`<option ${state.scale===v?'selected':''}>${v}</option>`).join('')}</select><button data-period="-1" aria-label="Período anterior">‹</button><button data-period="1" aria-label="Próximo período">›</button><button data-period="0">Hoje</button><button data-action="expand-timeline" aria-label="Expandir cronograma" aria-pressed="false">⛶ Expandir</button></div></div><div class="legend">${['Levantamento','Proposta','Planejamento','Desenvolvimento','Homologação','Implantação'].map(p=>`<span><i style="background:${SGP.phaseColors[SGP.stages.indexOf(p)]}"></i>${p}</span>`).join('')}<span>◆ Entrega técnica / outros marcos</span><span style="color:#d24d63">┆ Hoje</span></div><div class="timeline-scroll" tabindex="0" aria-label="Cronograma com rolagem horizontal"><div class="timeline" style="min-width:${state.scale==='Semana'?435+n*110:1020}px"><div class="trow theader"><div class="tlabel"><span>Frente / Demanda</span><span>Responsável</span><span>Início</span><span>Fim prev.</span></div><div class="thead-track" style="position:relative">${periods.map(p=>`<div class="tick" style="flex:${SGP.days(p.start,p.end)}"><strong>${state.scale==='Semana'?SGP.fmt(p.start):new Intl.DateTimeFormat('pt-BR',{month:'short',year:'numeric',timeZone:'UTC'}).format(SGP.date(p.start))}</strong><span>${state.scale==='Trimestre'?'Trimestre':state.scale==='Semana'?'Semana':'01　　08　　15　　22'}</span></div>`).join('')}${todayLine?`<span class="today-tag" style="left:${left(today)}%">Hoje</span>`:''}</div></div>${groups.map((g,i)=>{const ds=demands.filter(d=>d[key]===g);if(!ds.length)return '';return `<div class="trow group-row"><div class="tlabel" style="--front:${SGP.colors[i%5]}"><button data-collapse-group="${e(g)}">${state.closed?.includes(g)?'▸':'▾'} ${e(g)} <span style="color:#8a9cad;font-weight:400">(${ds.length})</span></button></div><div class="track" style="--ticks:${n*4}">${todayLine}</div></div>${state.closed?.includes(g)?'':ds.map(row).join('')}`}).join('')||'<div class="empty">Nenhuma demanda para os filtros selecionados.</div>'}</div></div></section>`;
};
